packages:
  - packages/*

allowBuilds:
  simple-git-hooks: true

strictPeerDependencies: false
minimumReleaseAge: 120
publicHoistPattern:
  - '*types*'
  - '*eslint*'
  - '@commitlint/*'
  - cz-git
  - czg
  - '*semantic-release*'
  - tslib
