name: Lint

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/build-setup

      - name: Build Config
        run: pnpm build:all

      - name: Lint
        run: pnpm lint
